commit changes
andrewmpho47/salesinvoice pull request #1
Opened 2023-05-04 14:00 UTC by andrewmpho47

Waiting for Trevor to approve the pull request

2023-05-09 12:29 UTC, TrevorMal commented
Pull request you tell the reviewer what changes are being introduced.

2023-05-09 12:32 UTC, TrevorMal commented
Am seeing also log files those don't belong in the repo.

2023-05-09 12:39 UTC, TrevorMal requested changes

2023-05-09 12:39 UTC, TrevorMal commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
IDE Configurations files should be excluded and you make use of .gitignore file to excluded certain files.

2023-05-09 12:40 UTC, TrevorMal commented
Check code styling and access modifiers for some beans.

2023-05-10 14:47 UTC, andrewmpho47 commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Managed to use gitignore to untrack the IDE configurations and deleted logs that where auto generated by IntelliJ

2023-05-17 08:20 UTC, merged